# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  # - name: What we do
  #   submenu:
  #     - name: What we do now
  #       link: /whatwedo/whatwedonow
  #     - name: Plans for the future...
  #       link: /whatwedo/plansforthefuture
  #     - name: Within Sierra Leone
  #       link: /whatwedo/withinsierraleone
  #     - name: Across Africa
  #       link: /whatwedo/acrossafrica
  #     - name: Bee-keeping
  #       link: /whatwedo/beekeeping
  - name: Our Story
    link: /story
  - name: Underlying Principles
    link: /principles
  - name: Impact
    link: /impact
  - name: What we do
    link: /about
  - name: How you can help
    link: /donate


